### ISSUE TITLE
SuiteSparse easyblock fails when using Python 3

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#1784]
When running `eb` on top of Python 3.6.8:

```
$ eb SuiteSparse-5.4.0-foss-2019a-METIS-5.1.0.eb
...
== configuring...
ERROR: Traceback (most recent call last):
  File "/home/kehoste/easybuild-framework/easybuild/main.py", line 112, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/kehoste/easybuild-framework/easybuild/framework/easyblock.py", line 3046, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/kehoste/easybuild-framework/easybuild/framework/easyblock.py", line 2954, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/kehoste/easybuild-framework/easybuild/framework/easyblock.py", line 2824, in run_step
    step_method(self)()
  File "/home/kehoste/easybuild-easyblocks/easybuild/easyblocks/s/suitesparse.py", line 113, in configure_step
    for (var, val) in cfgvars.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by boegel** [comment]
fixed in #1796
