### ISSUE TITLE
CP2K easyblock fails when using Python 3

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#1785]
```
$ CP2K-6.1-foss-2019a.eb
...
== testing...
ERROR: Traceback (most recent call last):
  File "/home/kehoste/easybuild-framework/easybuild/main.py", line 112, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/kehoste/easybuild-framework/easybuild/framework/easyblock.py", line 3046, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/kehoste/easybuild-framework/easybuild/framework/easyblock.py", line 2954, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/kehoste/easybuild-framework/easybuild/framework/easyblock.py", line 2824, in run_step
    step_method(self)()
  File "/home/kehoste/easybuild-easyblocks/easybuild/easyblocks/c/cp2k.py", line 702, in test_step
    test_core_cnt = min(self.cfg.get('parallel', sys.maxint), 4)
AttributeError: module 'sys' has no attribute 'maxint'
```

**Comment by boegel** [comment]
fixed in #1795
