### ISSUE TITLE
GROMACS easyblock does not work with `--module-only`

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyblocks#2399]
Trying to rebuild the module leads to
```
== configuring [skipped]
== building [skipped]
== testing [skipped]
== installing [skipped]
== taking care of extensions [skipped]
== restore after iterating...
== postprocessing [skipped]
== sanity checking...
ERROR: Traceback (most recent call last):
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3412, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/easyblocks/g/gromacs.py", line 711, in run_all_steps
    return super(EB_GROMACS, self).run_all_steps(*args, **kwargs)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3311, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3166, in run_step
    step_method(self)()
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/easyblocks/g/gromacs.py", line 589, in sanity_check_step
    lib_files.extend([
  File "/project/def-sponsor00/ocaisa/easybuild/software/EasyBuild/4.3.4/lib/python3.8/site-packages/easybuild/easyblocks/g/gromacs.py", line 590, in <listcomp>
    'lib%s%s.%s' % (x, suff, self.libext) for x in libnames + mpi_libnames for suff in suffixes
AttributeError: 'EB_GROMACS' object has no attribute 'libext'
```

**Comment by ocaisa** [comment]
There will be a similar problem with `self.lib_subdir` (which is a little harder to fix)
