### ISSUE TITLE
crash when using --module-only with easyconfig using PythonBundle

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyblocks#2446]
```
$ eb antiSMASH-5.1.2-foss-2019b-Python-3.7.4.eb --module-only
ERROR: Traceback (most recent call last):
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3633, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3531, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3386, in run_step
    step_method(self)()
  File "/lib/python2.7/site-packages/easybuild_easyblocks-4.3.5.dev0-py2.7.egg/easybuild/easyblocks/generic/pythonbundle.py", line 173, in sanity_check_step
    super(Bundle, self).sanity_check_step(*args, **kwargs)
  File "/llib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 2524, in sanity_check_step
    self._sanity_check_step(*args, **kwargs)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3053, in _sanity_check_step
    self._sanity_check_step_extensions()
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.5.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 2926, in _sanity_check_step_extensions
    res = ext.sanity_check_step()
  File "/data/gent/400/vsc40023/easybuild_easy_installed/lib/python2.7/site-packages/easybuild_easyblocks-4.3.5.dev0-py2.7.egg/easybuild/easyblocks/generic/pythonpackage.py", line 822, in sanity_check_step
    exts_filter = (orig_exts_filter[0].replace('python', self.python_cmd), orig_exts_filter[1])
TypeError: replace() argument 2 must be str, not None
```

**Comment by boegel** [comment]
That's a side effect of now also running the sanity check for extensions under `--module-only`, see https://github.com/easybuilders/easybuild-framework/pull/3655

**Comment by boegel** [comment]
`eb Python-3.9.5-GCCcore-10.3.0.eb --module-only` is broken in the same way, so this is worth fixing ASAP...
